---
- name: Install Ansible pip requirements.
  become: yes
  apt:
    name: "{{ package }}"
    state: present
    install_recommends: no
  with_items:
    - python-all
    - python-pkg-resources
    - python-pip
    - python-virtualenv
  loop_control:
    loop_var: package
  tags:
    - python
    - python2
    - virtualenv
    - pip
  retries: 10
  register: packages_installed
  until: packages_installed is succeeded

- pip:
    name: "{{ module }}"
  with_items:
    - setuptools
    - docker
    - wheel
  loop_control:
    loop_var: module
  tags:
    - docker-py
  retries: 10
  register: modules_installed
  until: modules_installed is succeeded
