---
#
# Set facts.
#

- name: "Set 'docker_ee_repository' fact."
  set_fact:
    docker_ee_repository: "{{ docker_ee_release_channel }}{% if docker_ee_version != 'latest' %}-{{ docker_ee_version }}{% endif %}"

- name: "Set 'docker_ee_package' fact."
  set_fact:
    docker_ee_package: "docker-ee{% if docker_ee_package_version != 'latest' %}-{{ docker_ee_package_version }}{% endif %}"

#
# Remove previously installed versions of Docker.
#
- name: "Ensure old versions of Docker are not installed."
  package:
    name: '{{ package }}'
    state: absent
  with_items:
    - containerd
    - docker
    - docker-ce
    - docker-common
    - docker-engine
    - docker-libnetwork
    - docker-runc
    - yast2-docker
    - runc
  loop_control:
    loop_var: package
